### ISSUE TITLE
plot returns ggplot object

### ISSUE THREAD

**Issue by alanocallaghan** [pkimes/sigclust2#4]
Thanks for your useful package, I have gotten quite a bit of use out of it.

One minor bugbear I have with respect to this package is that the `plot()` generic actually returns a ggplot object and does not use native graphics. While the ggplot version is preferable on its own for the most part, for incorporating into other base plots it is quite tricky, for example in `heatmap.2/3/plus()`: http://s11.postimg.org/t4ohfiwpv/heatmap3_example.png

My suggestion would be to migrate the current plot function to `ggplot.shc()` and define a new `plot.shc()` that uses base graphics. I have done some preliminary work on implementing this and would be happy to contribute if you agree with this suggestion.

Thanks
Alan

**Comment by pkimes** [comment]
Sorry for taking so long to get back!

The suggestion sounds reasonable, and I'm definitely open to the idea. If you're still interested in contributing, I'd be happy to take a look. If you could fork from the `devel` branch and open a pull request that would be great.

**Comment by alanocallaghan** [comment]
Thanks Patrick, I'll get cracking shortly.
